services:
  mongodb:
    image: mongo:6-jammy
    restart: always
    ports:
      - '8100:27017'
    volumes:
      - dbdata6:/data/db
    command: ["mongod", "--bind_ip", "0.0.0.0"]

  sessions_hnh:
    container_name: redis_session
    image: redis:7.2-alpine
    restart: always
    ports: 
    - "8008:6379"
    volumes:
    - $PWD/redis_data:/data

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

volumes:
  dbdata6: