services:
  mongodb:
    image: mongo:6-jammy
    restart: always
    ports:
      - '8100:27017'
    volumes:
      - dbdata6:/data/db
    command: ["mongod", "--bind_ip", "0.0.0.0"]

  sessions_hnh:
    container_name: redis_session
    image: redis:7.2-alpine
    restart: always
    ports: 
    - "8008:6379"
    volumes:
    - $PWD/redis_data:/data

volumes:
  dbdata6: